### ISSUE TITLE
When recreating a user that existed before there is a conflict with guid and uuid

### ISSUE THREAD

**Issue by whysthatso** [cashongo/chef-cog_security#4]
the home directory is not removed during user removal. it seems upon recreation of that user, those files are being reused but do not have the new user's guid and uuid.

either we delete the home dir or we recreate the users with static id's, where the former is preferred, and the latter stinks to the sky.

**Comment by ljesmin** [comment]
So, if we remove home directory, then it should be fine ? 
I did not see any settings about not-reusing-uids and gids. Easiest way to do it is not to remove users but lock them.
